# Generated by Django 4.2.1 on 2023-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname_user',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth_user',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail_user',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_user',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
