# Generated by Django 4.2.1 on 2023-05-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0002_remove_profile_name_user_remove_profile_surname_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname_user',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
