# Generated by Django 4.2.1 on 2023-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0006_ticket_date_ticket_destination1_ticket_destination2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
