# Generated by Django 4.2.1 on 2023-05-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0007_profile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
