# Generated by Django 4.2.1 on 2023-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0009_rename_user_id_buyticket_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyticket',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
