# Generated by Django 4.2.1 on 2023-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0010_buyticket_date_of_birth_buyticket_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
