# Generated by Django 4.2.1 on 2023-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPTProject', '0011_ticket_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
